### ISSUE TITLE
Doesn't work with Marked 7.0.0

### ISSUE THREAD

**Issue by fu-sen** [fu-sen/strapdown#7]
I checked the Marked 6.0.0 release, but when I applied it to Strapdown.js it doesn't work.
This update will be put on hold until the cause is determined.

**Comment by fu-sen** [comment]
Marked v7.0.0 has been released, but the problem continues.

**Comment by fu-sen** [comment]
I decided that it was no longer easy to continue this project, so I decided to archive it.

**Comment by fu-sen** [comment]
Marked 7.0.1 resolves this issue.

**Comment by xrat** [comment]
Also thanks for revisiting your decision to archive your repo!
